### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by benfogiel**
Created unit tests for the following functions: read, write, align, extract, subtract, and combine.

What they do:
All of these tests invoke their respective function to create an output. They then check the type of the output files and the length. All but read and write compare their current output to a known true output with FITSDiff which will compare every value of each fits file and returns a detailed report if there are any differences.  These true outputs are stored in the directory "fixtures/comparativeData" and they were generated using either "fixtures/residuals" or "fixtures/science". Lastly, the click commands for each function is tested ensuring that click can successfully call the respective function.

Execution:
To run these tests, one simply needs to run `sdi test -n functionName` if no function name is given, it will run all of the tests. Note: function name "fitsio" will run both read and write. At this time, it is not possible to run tests on read and write separately (I don't think this should be an issue)

### CODE REVIEW

**Comment by varun-magesh** [comment]
I think I might be using your branch wrong. Currently, when I run `sdi test --help`, I get the old help dialog (no `-n` option), and `sdi test` says "3 tests completed, done." I think I should be seeing more tests, and the `-n` option.

Steps to reproduce:
1. Create a venv.
2. Clone a fresh sdi.
3. Checkout to the Unit-Testing branch.
4. Run sdi test.

**Comment by benfogiel** [comment]
> I think I might be using your branch wrong. Currently, when I run `sdi test --help`, I get the old help dialog (no `-n` option), and `sdi test` says "3 tests completed, done." I think I should be seeing more tests, and the `-n` option.
> 
> Steps to reproduce:
> 
> 1. Create a venv.
> 2. Clone a fresh sdi.
> 3. Checkout to the Unit-Testing branch.
> 4. Run sdi test.

If you run `git pull origin Unit-Testing` you should have up to date Unit Testing branch. Not sure why this doesn't happen automatically but I did this and it worked

**Comment by varun-magesh** [comment]
I'm still having this issue. We should debug this weekend and figure it out because this feature is important.

**Comment by benfogiel** [comment]
Fixed a really stupid spelling error that didn't prompt any error but didn't compare outputs within two test functions

**Comment by benfogiel** [comment]
upgraded the subtract test function by adding a fits image to the input so when the subtract occurs, it doesn't simply output a blank image (previously we were only using one image). This should make the subtract test more effective

**Comment by EdgarMao** [comment]
@varun-iyer How are we planning to implement these programs? Will they become a part of the CI/CD workflow like you planned for pylint in issue #78 ? If that is needed I can provide some help since I looked into how to setup CI for pylint.

**Pull request merged**
