### PR TITLE
Click command and --help command clarity

### PR DESCRIPTION
**Pull request by JasperWebb**
This version of subtract was missing the @.click function to select the method of subtraction.  I added it from a different version.
Made --help command easier to read.  I added description for the argument 'method' and line breaks to stop lines from running into each other.

### CODE REVIEW

**Comment by JasperWebb** [comment]
This is my first pull request so I'm not sure if I did it right.

**Review by varun-magesh — COMMENTED** [review]
lgtm

**Review by EdgarMao — APPROVED** [review]
This looks good to me!

**Review by PK0207 — APPROVED** [review]
looks good to me, thanks for the fix.

**Pull request merged**
